# Generated by Django 4.1.1 on 2022-09-21 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilioModelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(help_text='Įveskite automobilio markę', max_length=50, verbose_name='Markė')),
                ('modelis', models.CharField(help_text='Įveskite automobilio modelį', max_length=50, verbose_name='Modelis')),
            ],
            options={
                'verbose_name': 'Automobilio modelis',
                'verbose_name_plural': 'Automobilių modeliai',
            },
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valstybinis_nr', models.CharField(max_length=7, verbose_name='Valstybinis_NR')),
                ('VIN_kodas', models.CharField(help_text='Įveskite VIN kodą', max_length=200, verbose_name='VIN_kodas')),
                ('klientas', models.CharField(max_length=200, verbose_name='Klientas')),
                ('automobilio_modelis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.automobiliomodelis')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
            },
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=200, verbose_name='Pavadinimas')),
                ('kaina', models.FloatField(verbose_name='Kaina')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('suma', models.FloatField(max_length=200, verbose_name='Suma')),
                ('status', models.CharField(blank=True, choices=[('p', 'Priimtas'), ('v', 'Vykdomas'), ('i', 'Įvykdytas'), ('a', 'Atmestas')], default='p', help_text='Statusas', max_length=1)),
                ('automobilis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzsakymas', to='autoservice.automobilis')),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
            },
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.IntegerField(verbose_name='Kiekis')),
                ('kaina', models.FloatField(max_length=200, verbose_name='Kaina')),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzsakymoeilute', to='autoservice.automobilis')),
                ('paslauga_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.paslauga')),
                ('uzsakymas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.uzsakymas')),
            ],
            options={
                'verbose_name': 'Užsakymo eilutė',
                'verbose_name_plural': 'Užsakymų eilutės',
            },
        ),
    ]
