# Generated by Django 4.1.1 on 2022-09-21 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_alter_uzsakymoeilute_uzsakymas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='auto',
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='automobilis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.automobilis'),
        ),
    ]
